language: node_js
os: windows
node_js:
  - 18.17.0
install:
  - yarn
services:
  - docker

before_install:
  - docker build -t nawaf83/youtube-stats -f Dockerfile.dev .
  
script:
  - docker run nawaf83/youtube-stats npm run build
  
